name: Build and upload to PyPI

on:
  workflow_dispatch:
  schedule:
    # First day of every month, you know, for automatic updates etc.
    - cron: "0 0 1 * *"
  push:
    tags:
      - "*"

env:
  DOCKER_BUILDKIT: 1

jobs:
  build_and_upload:
    name: Build and upload
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/dibber

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: "3.13"

      - uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1

      - name: Update package version
        run: |
          VERSION=$(git tag --points-at HEAD | head -n1)
          uv version "$VERSION"

      - name: Build
        run: uv build

      - name: Publish package distributions to PyPI
        if: success() && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
